### PR TITLE
Fix file server crash

### LINKED ISSUE #19: crash when visiting dir with index.html
Try running 'file_server' in the deno root directory and visiting http://0.0.0.0:4500/website

```
> file_server
HTTP server listening on http://0.0.0.0:4500/
[2018-12-12 10:07:09] "GET /third_party HTTP/1.1" 200
[2018-12-12 10:07:15] "GET /third_party/v8 HTTP/1.1" 200
[2018-12-12 10:07:19] "GET /third_party/v8/README.md HTTP/1.1" 200
[2018-12-12 10:07:52] "GET /third_party/v8/AUTHORS HTTP/1.1" 200
[2018-12-12 10:08:56] "GET /third_party/v8/.gn HTTP/1.1" 200
[2018-12-12 10:09:02] "GET /build_extra HTTP/1.1" 200
TypeError: Cannot read property 'status' of undefined
    at serverLog (file:///Users/rld/.deno/deps/https/deno.land/x/net/file_server.ts:182:71)
    at http_1.listenAndServe (file:///Users/rld/.deno/deps/https/deno.land/x/net/file_server.ts:204:5)
```

### PR DESCRIPTION
**Pull request by bartlomieju**
Fix #19

### CODE REVIEW

File: file_server.ts [hunk 1]
```diff
@@ -109,8 +109,7 @@ async function serveDir(req: ServerRequest, dirPath: string, dirName: string) {
   for (const info of fileInfos) {
     if (info.name === "index.html" && info.isFile()) {
       // in case index.html as dir...
-      await serveFile(req, info.path);
-      return;
+      return await serveFile(req, info.path);
```
Comment (ry) [inline file_server.ts]: Can we get a test?
